### ISSUE TITLE
Bookending tests

### ISSUE THREAD

**Issue by mosesyhc** [bandframework/surmise#125]
Isolating bookending tests in this issue. 

              The tox testing tasks and CI actions will need revisiting as part of this work.  Note that we have agreed that the the CI actions should use the latest version of its dependencies rather than be fixed to specific versions.  This should be compatible with using dependabot.

              Optionally, we can add a new CI test action that uses the oldest versions of each dependency so that our tests are bookending all supported versions.

_Originally posted by @jared321 in https://github.com/bandframework/surmise/issues/74#issuecomment-2187329814_

**Comment by jared321** [comment]
This work was done on PR #135 and is now in `v0.3-update`.  It will make its way to main as part  of the release process.  Closed.
