### ISSUE TITLE
Print statements propogate from methods to console

### ISSUE THREAD

**Issue by MattPlumlee** [bandframework/surmise#2]
When running methods, the print statement used by developers will show up.  In Example 3, we get statements to console like
`PCGP considering  2 PCs`
and
```
(1000, 1)
(21, 1000)
```
 There should be a way for a user to suppress these print statements in `surmise` done by methods that are still under development that do not have good error handling.

**Comment by MattPlumlee** [comment]
One suggestion to do this is Alexander Chzhen's answer on "https://stackoverflow.com/questions/8391411/how-to-block-calls-to-print"

**Comment by mosesyhc** [comment]
Completed by fulfilling #71
