### ISSUE TITLE
`rnd()` call error in `emulator.predict()` object 

### ISSUE THREAD

**Issue by mosesyhc** [bandframework/surmise#29]
The sample draw functionality `rnd()` is coded in the `emulator.predict` object, but neither methods (`PCGP` or `PCGPwM`) pass such a function.

Reproducing code:
```
from surmise.emulation import emulator
import numpy as np

x = np.arange(10)
theta = np.arange(20).reshape((20, 1))

f = np.random.normal(size=(20, 10))
emu = emulator(x=x, theta=theta, f=f,
               method='PCGP',
               args={'warnings': True})

pred = emu.predict()
samples = pred.rnd(1000) 
```

**Comment by mosesyhc** [comment]
@ozgesurer: Should there be a sampler within emulator object?  It seems that we never use the `rnd()` from an emulator, but always from the calibrator. 

If so, we can do a minimal change by switching from a hard error to a warning, so it does not crash when `.rnd()` is called somehow.
(https://github.com/bandframework/surmise/blob/v0.2-staging/surmise/emulation.py#L1072)

**Comment by ozgesurer** [comment]
@mosesyhc I did not include this functionality to surmise and I am not aware of the reason why we have it. Please feel free to make any necessary changes for your research as I don't use surmise for any of my research projects.
