### ISSUE TITLE
List of calibration methods for next release

### ISSUE THREAD

**Issue by mosesyhc** [bandframework/surmise#54]
Here is my attempt to list all changes in calibration methods for review, following the same format for emulation methods.

@ozgesurer, @MattPlumlee may be best to address these.

**To include/review:**
- [x] ~~[calibrationmethods/mlbayes](https://github.com/surmising/surmise/blob/development/calibrator/mlbayes/surmise/calibrationmethods/mlbayes.py)~~
- [x] [developsk/directbayes](https://github.com/surmising/surmise/blob/developsk/surmise/calibrationmethods/directbayes.py)

**To remove:**
-

**Comment by mosesyhc** [comment]
@ozgesurer Is `mlbayes` a method we should add for the release?  Thanks.

**Comment by ozgesurer** [comment]
@mosesyhc No need to include mlbayes to the next release. Given that there is not interest for the development of that approach, I will keep a copy for my own records and then remove that branch from surmise soon.
