### ISSUE TITLE
Other unmerged codes (plotting and diagnostics)

### ISSUE THREAD

**Issue by mosesyhc** [bandframework/surmise#56]
There are codes developed for diagnostics and plotting living in MCC9XXX/surmise 2 years ago.

Are any of these developed codes useful for the next release? Or should this be tabled until the next next release?

Thoughts: @ozgesurer, @wildsm, @MattPlumlee

**Comment by ozgesurer** [comment]
@mosesyhc If you think that those plots are useful for your research, I think we can include.

**Comment by mosesyhc** [comment]
@ozgesurer My inclination is to review these codes post v0.2, since I have no experience with the diagnostic/plotting codes that were developed and it will need more time.

**Comment by mosesyhc** [comment]
Closed issue as the unmerged codes are not included in current planning.
