### ISSUE TITLE
Update links to surmise if org transferred

### ISSUE THREAD

**Issue by wildsm** [bandframework/surmise#76]
We will need to update links in a number of places if the surmise repo is moved from the surmising org. 
This issue seeks to summarize them:

- [x] Update workflow in the data gathering repo https://github.com/surmising/surmisedatacollection
- [x] Ensure that the data gathering repo still works after the move
- [x] Update pypi (maybe in conjunction with release and/or the pypi publish action)
- [x] Do a recursive grep for surmising and replace with bandframework in the develop branch of https://github.com/bandframework/surmise
- [x] Do a recursive grep for surmising and replace with bandframework in the develop branch of https://github.com/bandframework/bandframework
- [x] Do a recursive grep and replace at https://github.com/bandframework/privateband
- [x] Update submodule in develop branch of https://github.com/bandframework/bandframework
- [x] Update https://surmise.readthedocs.io
- [x] #80

We would be following [this process](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) for repo transfer

@ozgesurer @mosesyhc feel free to edit and refine the above

**Comment by wildsm** [comment]
I have temporarily moved the repo, it was straightforward; we can always move back after hearing from all developers.
I will now start some of the above

**Comment by wildsm** [comment]
>  Ensure that the data gathering repo still works after the move

So it works, but did not inherit the (little) data from surmising/surmise.

See the two separate directories 
https://github.com/surmising/surmisedatacollection/tree/github-repo-stats

I suspect once could include the surmising data in the bandframework data, but I am not going down this line at the moment, feel free to take a look.

**Comment by wildsm** [comment]
Established the https://github.com/bandframework/bandframework/tree/dev/testsurmisemove branch to address
 Do a recursive grep for surmise/surmise in the develop branch of https://github.com/bandframework/bandframework

**Comment by wildsm** [comment]
>Do a recursive grep for surmising and replace with bandframework in the develop branch of https://github.com/bandframework/surmise

This is #78

**Comment by wildsm** [comment]
> Do a recursive grep and replace at https://github.com/bandframework/privateband

The only references to surmising/surmise are in `Presentations/`, keeping those.

**Comment by wildsm** [comment]
For 

> #80 

We've updated the surmising/.github/profile/README.md to display this info at 
https://github.com/surmising

**Comment by mosesyhc** [comment]
Closing issue upon completion
