### ISSUE TITLE
Add a surmise repo to surmising org that has a readme directing people to the new repo location?

### ISSUE THREAD

**Issue by mosesyhc** [bandframework/surmise#80]
@wildsm: I was going to add the new repo and a readme but has no administrative access to surmising.

**Repository Migration**

surmise has now migrated to [bandframework/surmise](https://github.com/bandframework/surmise).

**Comment by wildsm** [comment]
Invited you to surmising org, didn't realize that had not been done.

However, do we really want to make a "surmise" repo with a readme?
Will the autoredirect fail?

**Comment by mosesyhc** [comment]
I think now I officially broke the autoredirect...

**Comment by wildsm** [comment]
I suggest looking to see whether deleting the new repo will restore things.
I can imagine that autoredirect is helpful for many cases, but I have not researched the implications.

**Comment by mosesyhc** [comment]
> I suggest looking to see whether deleting the new repo will restore things. I can imagine that autoredirect is helpful for many cases, but I have not researched the implications.

It does! Autoredirect is restored.
