### ISSUE TITLE
resync readthedocs web integration

### ISSUE THREAD

**Issue by mosesyhc** [bandframework/surmise#96]
ReadtheDocs integration was originally set up before migration to bandframework.  After a recent notice from RTD, the integration requires a resync and I do not have admin access to bandframework/surmise.

@wildsm: Would you prefer me to add you as a RTD maintainer, so that you can resync the integration?  I am open to other suggestions.

**Comment by wildsm** [comment]
@MattPlumlee @ozgesurer - I don't see surmise on my readthedocs projects dashboard; can you please add moses and me (via my github @wildsm)?

**Comment by ozgesurer** [comment]
@wildsm You should have received a maintainer invitation from rtd a couple minutes ago. I sent an invitation to Moses a couple months ago. I think the admin access should be through surmise.

**Comment by mosesyhc** [comment]
Yes. To clarify, I am a maintainer on RTD, but I don't have (bandframework/surmise) access to resync the web integration.

**Comment by ozgesurer** [comment]
I also don't see surmise settings now from my GitHub account. So, I am not able to resync as well.

**Comment by mosesyhc** [comment]
Integration webhook is now fixed. thanks, @wildsm .
